# Welcome to Bridgetown!
#
# This config file is for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `bin/bridgetown start`. If you change this file, please restart the server process.
#
# For reloadable site metadata like title, SEO description, social media
# handles, etc., take a look at `src/_data/site_metadata.yml`
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

url: "https://stephendolan.com"

base_path: "/"

permalink: pretty

timezone: America/New_York

defaults:
  - scope:
      collection: "writing"
    values:
      layout: "prose"
  - values:
      layout: "default"
      image: "/images/stephen.jpg"
      author:
        name: Stephen Dolan
        twitter: Stephen_Dolan

collections:
  timeline_events:
    sort_by: date
    sort_direction: descending
  writing:
    output: true
    sort_by: date
    sort_direction: descending

feed:
  collections:
    - writing
