app = "stephen-dolan"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  BRIDGETOWN_ENV = "production"

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.http_options.response.headers]
    Cache-Control = "public, max-age=432000"

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[experimental]
  allowed_public_ports = []
  auto_rollback = true