name: Auto-merge

on:
  workflow_dispatch:
  workflow_run:
    types:
      - completed
    workflows:
      - "CI"

jobs:
  automerge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: stephendolan/lucky_jumpstart/.github/workflows/automerge.yml@v1.0.0
