name: Auto-merge minor/patch
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  test:
    name: Auto-merge minor and patch updates
    runs-on: ubuntu-latest
    steps:
      - uses: stephendolan/dependabot-pr-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-minor: true
          merge-patch: true
          approve-neutral-check-status: true
