name: Auto-merge minor/patch
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  test:
    name: Auto-merge minor and patch updates
    runs-on: ubuntu-latest
    steps:
      - name: "Merge"
        uses: "nucleos/auto-merge-action@1.0.0"
        env:
          "GITHUB_TOKEN": ${{ secrets.GITHUB_TOKEN }}
