name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: prettier
        run: 
          - npm install -g prettier prettier-plugin-tailwindcss @shopify/prettier-plugin-liquid
          - npx prettier --check **/*.{js,md,liquid} --plugin=prettier-plugin-tailwindcss --plugin=@shopify/prettier-plugin-liquid

      - name: standardrb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: amoeba/standardrb-action@v4
