name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Prettier Plugins
        run: npm install @shopify/prettier-plugin-liquid prettier-plugin-tailwindcss

      - name: Run Prettier Checks
        uses: actionsx/prettier@v3
        with:
          args: --check **/*.{js,md,liquid} --plugin=@shopify/prettier-plugin-liquid

      - name: Run StandardRB Check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: amoeba/standardrb-action@v4
