name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check **/*.{js,md,liquid}
          - name: prettier
            uses: creyD/prettier_action@v4.3
            with:
              prettier_options: --check **/*.{js,md,liquid}
              prettier_plugins: "@shopify/prettier-plugin-liquid prettier-plugin-tailwindcss"
          - name: standardrb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: amoeba/standardrb-action@v4
